name: Create envfile

on: [ push ]

jobs:

  create-envfile:
 
    runs-on: ubuntu-latest
 
    steps:
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v2.0
      with:
        envkey_DEBUG: false
        envkey_SOME_API_KEY: "123456abcdef"
        envkey_BASE_URL: ${{ secrets.BASE_URL }}
        envkey_VARIABLE: ${{ vars.BASE_URL }}
        some_other_variable: foobar
        directory: .
        file_name: .env
        fail_on_empty: false
        sort_keys: false