name: Using GitHub Secrets

on: [push]

jobs:
    using-github-secrets:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Create .env file
              run: |
                  touch .env
                  echo "BASE_URL = ${{vars.BASE_URL}}" >> .env